mystoreapp/models.py
from . import db

class Category(db.Model):
    __tablename__ = 'categories'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'default.jpg')
    products = db.relationship('Product', backref='Category', cascade="all, delete-orphan")

    def __repr__(self):
        str = "ID: {}, Name: {}, Description: {}, Image: {}\n" 
        str = str.format(self.id, self.name, self.description, self.image)
        return str      
    
class Product(db.Model):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64),nullable=False)
    subname = db.Column(db.String(64),nullable=False)
    description = db.Column(db.String(500), nullable=False)
    size = db.Column(db.Text(64),nullable=False)
    image = db.Column(db.String(60), nullable=False)
    price = db.Column(db.Float, nullable=False)
    status = db.Column(db.Text)
    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'))
    
    def __repr__(self):
        str = "ID: {}, Name: {}, Description: {}, Image: {}, Price: {}, Category_ID: {}\n" 
        str = str.format(self.id, self.name, self.description, self.image, self.price, self.category_id)
        return str

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('product_id',db.Integer,db.ForeignKey('products.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'product_id') )

class Order(db.Model):
    __tablename__ = 'orders'
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime)
    firstname = db.Column(db.String(64))
    lastname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    totalcost = db.Column(db.Float)
    products = db.relationship("Product", secondary=orderdetails, backref="orders")
    
    def __repr__(self):
        str = "ID: {}, Date: {}, First Name: {}, Last name: {}, Email: {}, Phone: {},   Total Cost: {}\n" 
        str = str.format(self.id, self.date, self.firstname, self.lastname, self.email, self.phone, self.totalcost)
        return str

    

    

mystoreapp/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired

# form used in basket
class CheckoutForm(FlaskForm):
    firstname = StringField("Your first name", validators=[InputRequired()])
    lastname = StringField("Your last name", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    submit = SubmitField("Submit")

mystoreapp/__init__.py
#import flask - from the package import class
from flask import Flask, render_template
from flask_bootstrap import Bootstrap as Bootstrap4
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
app = Flask(__name__)

#create a function that creates a web application
# a web server will run this web application
def create_app():
    app.debug = True
    app.secret_key = 'BetterSecretNeeded123'

    #set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///mystoreapp.sqlite'

    #initialise db with flask app
    db.init_app(app)

    bootstrap = Bootstrap4(app)
    
    #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.main_bp)
    #from . import admin
    #app.register_blueprint(admin.admin_bp)
   
    return app

@app.errorhandler(404) 
# inbuilt function which takes error as parameter 
def not_found(e): 
  return render_template("404.html")

@app.errorhandler(500)
def internal_error(e):
  return render_template("500.html")

mystoreapp/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Product, Category, Order
from datetime import datetime
from .forms import CheckoutForm
from . import db

main_bp = Blueprint('main', __name__)
main_bp.secret_key = 'some_secret'

@main_bp.route('/')
def getAllProduct():
    products = Product.query.order_by(Product.id).all()
    categories = Category.query.order_by(Category.id).all()
    #statusnew = Product.query.filter(Product.status == 'new')
    return render_template('index.html', products=products, categories=categories)


#getProductByCategory
@main_bp.route('/products/<int:categoryid>')
def getByCategory(categoryid):
    categories = Category.query.order_by(Category.id).all()
    products = Product.query.filter(Product.category_id == categoryid)
    return render_template('productList.html', categories=categories, products=products)
#getProductDetail
@main_bp.route('/productDetail/<int:productid>')
def getProduct(productid):
    products = Product.query.filter(Product.id == productid )
    categories = Category.query.order_by(Category.id).all()
    return render_template('productDetail.html', categories=categories,products=products)


# Referred to as "Basket" to the user
@main_bp.route('/order', methods=['POST','GET'])
def order():
    categories = Category.query.order_by(Category.id).all()
    product_id = request.values.get('product_id')

    # retrieve order if there is one
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order( firstname='', lastname='', email='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for product in order.products:
            totalprice = totalprice + product.price
    
    # are we adding an item?
    if product_id is not None and order is not None:
        product = Product.query.get(product_id)
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('This item already in basket')
            return redirect(url_for('main.order'))
    return render_template('order.html', order = order, totalprice=totalprice,categories=categories)

# Delete specific basket items
@main_bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id=request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        product_to_delete = Product.query.get(id)
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.order'))
        except:
            return 'Problem deleting item from order'
    return redirect(url_for('main.order'))

# Scrap basket
@main_bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.getAllProduct'))

@main_bp.route('/checkout', methods=['POST','GET'])
def checkout():
    categories = Category.query.order_by(Category.id).all()
    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.firstname = form.firstname.data
            order.lastname = form.lastname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for product in order.products:
                totalcost = totalcost + product.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you for ordering!')
                return redirect(url_for('main.getAllProduct'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form=form, categories=categories)

@main_bp.route('/products')
def search():
    categories = Category.query.order_by(Category.id).all()
    search = request.args.get('search')
    search = '%{}%'.format(search) 
    products = Product.query.filter(Product.name.like(search)).all()
    return render_template('productList.html', products=products,categories=categories)

mystoreapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="My Perfume App">
    <title>MY Perfume</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename= 'all.css') }}">
    <!-- Bootstrap version 4 -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <!--Material icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Animate.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
</head>

<body>
    <!-- putting header inside container will prevent full width navbar -->
    <header>
        <!--navbar creates a navigation bar -->
        <div class="container-fluid">
            <nav class="navbar navbar-expand-md navbar-light fixed-top" style="background-color: #ae6e06;">
                <div class="container-fluid">
                    <h1><a class="navbar-brand text-white animate__animated animate__fadeInDown" href="/">MY
                            PERFUME</a></h1>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    {% for category in categories %}
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                        <ul class="navbar-nav text-center ">
                            <li class="nav-item"><a href="{{ url_for('main.getByCategory', categoryid=category.id) }}"
                                    class="nav-link text-white fs-5 font-weight-bold">{{category.name}}</a>
                            </li>
                            {% endfor %}
                            <li class="nav-item">
                                <a href="{{ url_for('main.order') }}"
                                    class="nav-link text-white fs-5 font-weight-bold d-flex justify-content-center align-items-center"><span
                                        class="material-icons text-white">
                                        shopping_cart
                                    </span> <span class="d-block d-md-none">Basket</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>

        {% block head %}

        {% endblock %}

    </header>


    <!-- main page content goes in container -->
    <div class="container-fluid px-0" style="margin-top: 90px; ">
        <main>
            <div class="container px-0">
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" aria-label="Close" data-dismiss="alert" class="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    {{message}}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
            {% block main %}

            {% endblock %}
        </main>
    </div>

    <!-- Footer of the website -->
    <!-- Contact form -->
    <section>
        <div class="container-fluid contact d-flex align-items-center">
            <div class="container">
                <form class="row" method="post">
                    <div class="col-12 col-lg-4">
                        <h2 class="text-white font-weight-bold mb-3">My Perfume
                        </h2>
                        
                        <div class="col-12 mb-3 pl-0">
                            <label for="email" class="text-white form-label">My Perfume team acknowledges the Traditional Owners of the lands on which we meet and work, 
                                <br>both at our offices on Brisbane and our retail locations across Australia. We pay our respects to
                                <br> Elders- past, present and emerging- and honour their living culture and recognise their ongoing 
                                <br>connection to this beautiful country. 
                                <small class="font-weight-bold" data-message="acknowledges"></small></label>
                        </div>
                        
                    </div>
                </form>
            </div>
        </div>
    </section>
    <footer class="py-3" style="background-color: #ae6506;">
        <div class="d-flex justify-content-center">
            <p class="mb-1 text-white">Copyright &copy; 2023 MY PERFUME</p>
        </div>
    </footer>
    <!-- Footer -->


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

mystoreapp/templates/checkout.html
{% extends 'base.html' %}
{% from 'bootstrap4/form.html' import render_form %}

{% block main %}
    <section>  
        <div class="container">
            <div class="row margintop justify-content-center">
                <div class = "col-12 text-center">
                    <h1 style="margin-top: 60px;">Checkout</h1>
                    <p>
                        Thank you for your interest! <br>
                    Please provide your details so that one of our awesome staffs can contact you to finalise details and take payment.
                    Thank you!</br>
                    </p>
                </div>
            </div>
            <div class="row my-4 justify-content-center">
                <div class = "col-6">
                    {{ render_form(form) }}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mystoreapp/templates/index.html
{% extends 'base.html' %}

{% block head %}
<!--Jumbotron for Hero Section -->
<div class="jumbotron jumbotron-fluid card card-image hero d-flex justify-content-center">
    <div class="row justify-content-center mx-1">
        <div class="col-md-8">
            <div class="jumbotron shadow" style="background-color: #ffffff70;">
                <h2 class="text-center text-white">Find our best products</h2>
                <form class="form-inline d-flex flex-nowrap" action="{{url_for('main.search')}}">
                    <input class="form-control flex-grow-1 my-1" type="search" placeholder="Search for brands or items"
                        aria-label="Search for brands or items" name="search">
                    <button type="submit" class="flex-shrink-1 btn btn-main d-flex justify-content-center my-1"><span
                            class="material-icons">
                            search
                        </span>Search</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- hero section -->
{% endblock %}

{% block main %}
<section class="container">
    <!-- Quote of MY PERFUME-->
    <div class="quote text-secondary">
        <h6>“A perfume is like a piece of clothing, a message, a way of presenting oneself a costume that
            differs according to the
            woman who wears it.”
        </h6>
        <div class="d-flex justify-content-end">
            <h6>— Paloma Picasso</h6>
        </div>
    </div>
    <div class="border-bottom mb-3"></div>
    <!-- Brands We Sell -->
    <section class="d-md-block d-none mb-3">
        <h2 class="text-center my-4">Brands We Sell</h2>
        <div class="row justify-content-center align-items-center border">
            {% for category in categories %}
            <div class="col-2">
                <a href="{{ url_for('main.getByCategory', categoryid=category.id) }}"
                    class="nav-link text-white fs-5 font-weight-bold"><img class="w-100"
                        src="{{ url_for('static', filename='img/'+category.image) }}" alt=""></a>
            </div>
            {% endfor %}
        </div>
    </section>
    <!-- All Product -->
    <section>
        <h2 class="text-center">All Products</h2>
        <ul class="row d-flex px-5 mb-0">

            {% for product in products%}

            <li class="col-6 col-md-4 col-lg-3 position-relative my-3">
                <a class="text-dark" href="{{ url_for('main.getProduct', productid=product.id) }}">
                    {% if product.status %}
                    <h6 class="bg-dark text-white position-absolute position px-3 py-2">NEW</h6>
                    {% endif %}
                    <img src="{{ url_for('static', filename='img/'+product.image) }}" class="card-img-top"
                        style="height:60%">
                    <button type="button" class="btn btn-dark rounded-0 w-100 py-1 mb-2">
                        <h5>Buy Now</h5>
                    </button>
                    <h6 class="font-weight-bold">{{ product.name }}</h6>
                    <small>{{product.size}}</small>
                    <h5 class="font-weight-bold"> {{ "$%.2f"|format(product.price) }}</h5>
                </a>
            </li>
            {% endfor %}
        </ul>
    </section>
</section>
<!-- New Arrival -->
<section class="bg-light">
    <div class="container">
        <h2 class="text-center mb-4 pt-4">New Arrival</h2>
        <ul class="row d-flex px-5 mb-0">

            {% for product in products if product.status %}

            <li class="col-6 col-md-4 col-lg-3 position-relative my-3">
                <a class="text-dark" href="{{ url_for('main.getProduct', productid=product.id) }}">
                    <h6 class="bg-dark text-white position-absolute position px-3 py-2">NEW</h6>
                    <img src="{{ url_for('static', filename='img/'+product.image) }}" class="card-img-top"
                        style="height:60%">

                    <button type="button" class="btn btn-dark rounded-0 w-100 py-2 mb-2">
                        <h5>Buy Now</h5>
                    </button>
                    <h6 class="font-weight-bold">{{ product.name }}</h6>
                    <small>{{product.size}}</small>
                    <h5 class="font-weight-bold"> {{ "$%.2f"|format(product.price) }}</h5>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}

mystoreapp/templates/order.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row col-12 mt-2 my-4 justify-content-center">
            <h3>Shopping Basket</h3>
        </div>
        <!-- each tour on seperate row -->
        {% for product in order.products %}
            <div class="row shadow-md my-row mb-3 ">
                <div class="col-sm-10 card px-0">
                    <h5 class="card-header text-white" style="background-color: #e5b05a;">{{ product.name }} - {{ product.size}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{ url_for('static', filename=('img/' + product.image)) }}">
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->
                                <p class="card-text">{{ product.description }}</p>
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                    <!-- delete item button -->
                        <h5>{{ "$%.2f"|format(product.price) }}</h5>
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="{{product.id}}">
                            <input type="submit" value="Delete" class="btn btn-secondary mb-3">
                        </form> 
                </div>
            </div>
        {% endfor %}
        
        <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="mt-4">Total = {{ "$%.2f"|format(totalprice) }}</h5>
            </div>
        
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="{{ url_for('main.getAllProduct', _anchor='products_anchor') }}" class="btn btn-main mr-4">Home</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-main mr-4">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-secondary">Empty Basket</a>
            </div>
        </section>
    </div>
</section>
{% endblock %}

mystoreapp/templates/productDetail.html
{% extends 'base.html' %}

{% block main %}
<!-- Contains the main content of the website, divided into sections -->
<section>
  <nav aria-label="breadcrumb" class="container breadtop">
    <ol class="breadcrumb bg-white fs-5">
      <li class="breadcrumb-item"><a href="{{ url_for('main.getAllProduct', _anchor='products_anchor') }}"
          class="text-dark">Home</a></li>
      <li class="breadcrumb-item text-main active">Brands</a></li>
    </ol>
    <div class="border-bottom my-2"></div>
  </nav>
</section>
<section>
  {% for product in products %}
  <!--Product detail-->
  <div class="container margin">
    <div class="row flex-row align-items-center">
      <!-- product image -->
      <div class="col-12 col-md-6 mb-4">
        <img src="{{ url_for('static', filename='img/'+ product.image) }}" class="d-block w-100" alt="...">
      </div>

      <!-- product intro-->
      <div class="col-12 col-md-6">
        <h2 class="font-weight-bold">{{product.name}}</h2>
        <div class="border-bottom"></div>
        <h6 class="text-secondary mt-2">{{product.subname}}</h6>
        <p>{{product.description}}</p>
        <p class="h5 font-weight-normal mb-2"></p> {{ "$%.2f"|format(product.price) }}</p>
        <div class="chooseSize mb-2">
          <p class="mb-1">Size:</p>
            <button type="button" class="btn btn-outline-dark active mr-4">{{product.size}}</button>
            <form action="{{ url_for('main.order') }}">
              <input type="hidden" id="product_id" name="product_id" value="{{ product.id }}">
              <button class="btn btn-main btn-block fs-5 mt-3" type="submit" value="Add to Basket" style="height: 48px;">Add to
                Basket</button>
            </form>
        </div>
      </div>
    </div>
    {% endfor %}
    <!--Notice-->
    <div class="container row mb-5 px-0 mx-0">
      <div class="col-12 px-0">
        <div class="border-bottom my-3"></div>
        <h6 class="font-weight-bold">Product purchase instructions</h6>
        <p class="mb-3">The color of the product may vary slightly due to shooting, and the actual product is mainly
          shipped
          by the
          manufacturer. The photo of the product situation is for illustrative purposes only, only the main body of the
          product
          does not include other accessories, please refer to the specification content. MY PERFUME does its best to
          ensure
          that
          the listed items are fully stocked, but occasionally a product may be sold out. If the item you ordered is out
          of
          stock,
          we will notify you by email as soon as possible. Any order changes will be updated in the order total and
          shipping
          information.</p>
        <h6 class="font-weight-bold">Return Notice</h6>
        <p>In accordance with the provisions of the "Consumer Protection Law", all shoppers on the whole site enjoy the
          [seven-day
          hesitation period] (including holidays) when the goods arrive. If there is any problem with the product
          received,
          you
          can apply for a return within the hesitation period.</p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

mystoreapp/templates/productList.html
{% extends 'base.html' %}

{% block main %}
<section>
  <nav aria-label="breadcrumb" class="container breadtop">
    <ol class="breadcrumb bg-white fs-5">
      <li class="breadcrumb-item"><a href="{{ url_for('main.getAllProduct', _anchor='products_anchor') }}"
          class="text-dark">Home</a></li>
      <li class="breadcrumb-item text-main active">Brands</a></li>
    </ol>
  </nav>
</section>
<section>
  <div class="container">
    <div class="border-bottom my-2"></div>
    <ul class="row d-flex px-5 my-4">
      {% for product in products %}
      <li class="col-6 col-md-4 col-lg-3 position-relative">
        <a class="text-dark" href="{{ url_for('main.getProduct', productid=product.id) }}">
          {% if product.status %}
          <h6 class="bg-dark text-white position-absolute position px-3 py-2">NEW</h6>
          {% endif %}
          <img src="{{ url_for('static', filename='img/'+product.image) }}" class="card-img-top" style="height:60%">
          <button type="button" class="btn btn-dark rounded-0 w-100 py-1 mb-2">
            <h5>Buy Now</h5>
          </button>
          <h6 class="font-weight-bold">{{product.name}}</h6>
          <small>100ml</small>
          <h5 class="font-weight-bold"> {{ "$%.2f"|format(product.price) }}</h5>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</section>
{% endblock %}